Driver.out: TwoDimension.h ThreeDimension.h TwoDimension.cpp ThreeDimension.cpp Driver.cpp
	g++ -Wall Driver.cpp TwoDimension.cpp ThreeDimension.cpp  -o Driver.out

clean:
	rm *.o
	rm *.out

run:
	Driver.out